### ISSUE TITLE
Happy Ways

### ISSUE THREAD

**Issue by nodwan** [pythonlessons/RL-Bitcoin-trading-bot#2]
Hi, i‘m watching your work here now from time to time, and i‘m happy to see, someone try to build a tensor trading bot. i‘m not familiar with tensor, but i‘remember my study time, we was build a technical Kreatur what should walk forward, we was give only this job, to the NN, and later a lot epoche, it was move forward ... in a way where we was smile. 

so, maybe the same can happen here, the bot can teach himself for found the best strategy to to learn how to get food (for example btc) 

i‘dont know, this is possible ... but it‘s how i’thing, should work a AI. learn to get food in a live Szenario ...

**Comment by pythonlessons** [comment]
You just described the reinforcement learning method, that's exactly what I am using in this tutorial series :)
